Todo fixing
Arbuss/Pine pull request #13
Opened 2021-09-09 08:31 UTC by Arbuss

2021-09-09 12:40 UTC, nqkwey requested changes

2021-09-09 12:40 UTC, nqkwey commented on app/src/main/res/layout/item_progress.xml
> +        android:progressTint="@color/progress_bar_color" />
android:indeterminateTint

2021-09-09 12:40 UTC, nqkwey commented on app/src/main/java/com/rosberry/pine/domain/SearchInteractor.kt
> +package com.rosberry.pine.domain
не забыть вынести общее из ImageInteractor и SearchInteractor

2021-09-09 12:40 UTC, nqkwey commented on app/src/main/java/com/rosberry/pine/ui/search/SearchFragment.kt
> +class SearchFragment : ListedFragment<FragmentSearchBinding>() {
а ты не замечал, что у SearchFragment меняется цвет статусбара?

2021-09-09 12:40 UTC, nqkwey commented on app/src/main/java/com/rosberry/pine/ui/base/ListedFragment.kt
> +                            if (viewModel.currentPage != 0) {
тут можно вместо проверки viewModel.currentPage != 0 добавить просто тип ошибки, например, ImageError и ImageErrorPagination и для них уже показывать плейсхолдер/снэкбар

2021-09-09 12:40 UTC, nqkwey commented on app/src/main/java/com/rosberry/pine/ui/base/ListedViewModel.kt
> +    protected val _newPage = MutableStateFlow(listOf<ImageItem>())
тут, наверное, не нужно нижнее подчеркивание

2021-09-09 12:40 UTC, nqkwey commented on app/src/main/java/com/rosberry/pine/ui/base/ListedViewModel.kt
> +    private var screenWidth = 1
а почему инициализируешь единицей?

2021-09-09 12:40 UTC, nqkwey commented on app/src/main/java/com/rosberry/pine/ui/image/ImageItem.kt
> +        val isProgress: Boolean = false
зачем нужен isProgress?

2021-09-09 12:40 UTC, nqkwey commented on app/src/main/java/com/rosberry/pine/ui/search/SearchFragment.kt
> +    override val viewModel: SearchViewModel by viewModels()
Также мне тут пришла великолепная идея показывать клавиатуру при переходе на поиск, как думаешь?

2021-09-09 12:40 UTC, nqkwey commented on app/src/main/java/com/rosberry/pine/ui/search/SearchViewModel.kt
> +            if (lastQuery?.equals(query) == false) {
lastQuery?.equals(query) == false выглядит потрясающе, конечно 
это просто комментарий

2021-09-09 12:40 UTC, nqkwey commented on app/src/main/java/com/rosberry/pine/ui/search/SearchViewModel.kt
> +class SearchViewModel @Inject constructor(
добавить, чтобы старый запрос отменялся, когда пользователь начал искать что-то новое

2021-09-10 04:37 UTC, Arbuss commented on app/src/main/java/com/rosberry/pine/ui/base/ListedViewModel.kt
> +    private var screenWidth = 1
lateinit

2021-09-10 04:42 UTC, Arbuss commented on app/src/main/java/com/rosberry/pine/ui/base/ListedViewModel.kt
> +    private var screenWidth = 1
lateinit для примитивов нельзя, поэтому сделал Int?

2021-09-10 09:58 UTC, nqkwey requested changes

2021-09-10 09:58 UTC, nqkwey commented on app/src/main/java/com/rosberry/pine/domain/BaseInteractor.kt
> +open class BaseInteractor(private val connectionInfoInteractor: ConnectionInfoInteractor) {
думаю, тут правильно BaseImageInteractor

2021-09-10 09:58 UTC, nqkwey commented on app/src/main/java/com/rosberry/pine/ui/activity/AppActivity.kt
> +        window.statusBarColor = ContextCompat.getColor(applicationContext, R.color.status_bar_color)
это же можно указать в themes.xml

2021-09-13 11:05 UTC, nqkwey requested changes

2021-09-13 11:05 UTC, nqkwey commented on app/src/main/res/values-night/themes.xml
> +        <item name="android:statusBarColor" tools:targetApi="l">@color/additional_4_100</item>
а зачем здесь tools:targetApi?

2021-09-13 11:05 UTC, nqkwey commented on app/src/main/java/com/rosberry/pine/ui/search/SearchHistoryAdapter.kt
> +        notifyDataSetChanged()
почему через notifyDataSetChanged, если у тебя тут определен diffUtilCallback

2021-09-13 11:05 UTC, nqkwey commented on app/src/main/res/layout/fragment_search.xml
>          android:layout_marginVertical="4dp"
если загрузить какие-либо картинки и потом снова попробовать что-либо поискать - часть списка с картинка видна под списком с предыдущими поисками
![Screenshot_20210913-165909](https://user-images.githubusercontent.com/3686936/133072419-621645c1-8e3c-4ac3-9a00-2581173bd116.png)

2021-09-13 11:05 UTC, nqkwey commented on app/src/main/java/com/rosberry/pine/data/datasource/local/dao/SearchCacheDao.kt
> +    @Insert(onConflict = OnConflictStrategy.REPLACE)
тут получается, что если сделать 10 одинаковых поисков подряд, то в истории поиска будут показаны 10 одинаковых текстов
думаю, что id - это может быть текст поиска сам по себе

2021-09-13 11:05 UTC, nqkwey commented on app/src/main/java/com/rosberry/pine/data/datasource/local/dao/SearchCacheDao.kt
> +    fun getNLastItems(limit: Int): List<SearchCacheEntity>
getNLastItems - не самое лучшее название

2021-09-13 11:13 UTC, Arbuss commented on app/src/main/java/com/rosberry/pine/ui/search/SearchHistoryAdapter.kt
> +        notifyDataSetChanged()
Потому что тут нечего считать, я просто чищу список и добавляю другие 10 элементов

2021-09-13 11:15 UTC, Arbuss commented on app/src/main/java/com/rosberry/pine/data/datasource/local/dao/SearchCacheDao.kt
> +    @Insert(onConflict = OnConflictStrategy.REPLACE)
это надо будет обсудить на вопрос-ответ

2021-09-13 11:18 UTC, nqkwey commented on app/src/main/java/com/rosberry/pine/ui/search/SearchHistoryAdapter.kt
> +        notifyDataSetChanged()
тогда наличие SearchDiffUtilCallback в этом классе не имеет никакого смысла

2021-09-13 11:33 UTC, Arbuss commented on app/src/main/java/com/rosberry/pine/data/datasource/local/dao/SearchCacheDao.kt
> +    @Insert(onConflict = OnConflictStrategy.REPLACE)
добавить timestamp

2021-09-13 12:21 UTC, nqkwey requested changes

2021-09-13 12:21 UTC, nqkwey commented on app/src/main/java/com/rosberry/pine/data/repository/ImageRepository.kt
> +        return database.searchCacheDao()
что-то здесь снова getNLastItems

2021-09-14 04:14 UTC, nqkwey approved these changes

2021-09-14 04:28 UTC, merged