feature/PAA-129
Arbuss/Pine pull request #14
Opened 2021-09-14 07:16 UTC by Arbuss

2021-09-15 11:02 UTC, nqkwey requested changes

2021-09-15 11:02 UTC, nqkwey commented on app/src/main/res/layout/fragment_image.xml
> +            android:layout_marginEnd="16dp"
marginEnd не нужен, так как у тебя есть padding уже у LinearLayout

2021-09-15 11:02 UTC, nqkwey commented on app/src/main/res/layout/fragment_image.xml
> +    <ImageButton android:id="@+id/like_button"
Эта кнопка у меня отображается обрезанной, можешь посмотреть, в чем дело
![markup_6997](https://user-images.githubusercontent.com/3686936/133235896-fc855357-846f-4413-ad73-c7d4de05c20c.png)

2021-09-15 11:02 UTC, nqkwey commented on app/src/main/java/com/rosberry/pine/ui/base/ListedFragment.kt
> +        imageList?.adapter = ImageAdapter(viewModel)
тут вместо интерфейса можно просто лямбду прокидывать

2021-09-15 11:02 UTC, nqkwey commented on app/src/main/java/com/rosberry/pine/ui/fullscreen/FullscreenImageFragment.kt
> +            .fit()
а почему fit?

2021-09-15 11:02 UTC, nqkwey commented on app/src/main/java/com/rosberry/pine/ui/fullscreen/FullscreenImageFragment.kt
> +    private val IMAGE_KEY = "image_key"
тут студия будет ругаться на нейминг

2021-09-15 11:02 UTC, nqkwey commented on app/src/main/java/com/rosberry/pine/ui/fullscreen/FullscreenImageFragment.kt
> +                        .fit()
здесь тот же вопрос про fit

2021-09-15 11:02 UTC, nqkwey commented on app/src/main/java/com/rosberry/pine/ui/image/OnImageClickListener.kt
> +interface OnImageClickListener {
это можно заменить лямбдой в FeedFragment

2021-09-15 11:02 UTC, nqkwey commented on app/src/main/java/com/rosberry/pine/ui/base/ListedFragment.kt
> +    private fun setListClearObserver() {
когда возвращаешься на список фото - пустой список

2021-09-15 11:02 UTC, nqkwey commented on app/src/main/java/com/rosberry/pine/ui/fullscreen/FullscreenImageFragment.kt
> +        } catch (ignored: Exception) {
для чего try/catch? если обрботать OutOfMemory, то не самое лучшее решение

2021-09-15 11:02 UTC, nqkwey commented on app/src/main/java/com/rosberry/pine/ui/base/ListedViewModel.kt
> +            blurHash = BlurHashDecoder.decode(image.blurHash, screenWidth!!, imageHeight,
делать blurhash размером с оригинальную картинку занимает очень много времени. Что если делать его, например, размером image.width / 20, image.height / 20, а в ImageViewHolder делать его centerCrop. Должно работать нормально, раз там размер view подгоняется под размер картинки

2021-09-15 11:16 UTC, Arbuss commented on app/src/main/java/com/rosberry/pine/ui/fullscreen/FullscreenImageFragment.kt
> +        } catch (ignored: Exception) {
при выходе с экрана в момент подгрузки полной картинки он мог выдать что-то типа Target must no be null

2021-09-16 10:20 UTC, nqkwey requested changes

2021-09-16 10:20 UTC, nqkwey commented on app/src/main/java/com/rosberry/pine/ui/base/ListedFragment.kt
> +        lifecycleScope.launch(Dispatchers.Main) {
состояние списка не сохраняется, при возвращении всегда перекидывает наверх

2021-09-16 10:21 UTC, Arbuss commented on app/src/main/java/com/rosberry/pine/ui/base/ListedFragment.kt
> +        lifecycleScope.launch(Dispatchers.Main) {
Имелась в виду не позиция, а набор фотографий

2021-09-16 10:38 UTC, Arbuss commented on app/src/main/java/com/rosberry/pine/ui/base/ListedFragment.kt
> +        lifecycleScope.launch(Dispatchers.Main) {
state restoration policy у адаптера

2021-09-17 05:51 UTC, nqkwey requested changes

2021-09-17 05:51 UTC, nqkwey commented on app/src/main/java/com/rosberry/pine/ui/base/ListedFragment.kt
> +            repeatOnLifecycle(Lifecycle.State.CREATED) {
попробуй теперь зайти на экран фотографии -> вернуться -> снова перейти на экран фото -> вернуться -> белый экран

2021-09-17 09:29 UTC, nqkwey approved these changes

2021-09-17 09:31 UTC, merged