feaature/PAA-120
Arbuss/Pine pull request #17
Opened 2021-09-17 09:45 UTC by Arbuss

2021-09-17 11:55 UTC, nqkwey commented
@Arbuss конфликты

2021-09-17 12:08 UTC, nqkwey requested changes

2021-09-17 12:08 UTC, nqkwey commented on app/src/main/java/com/rosberry/pine/ui/fullscreen/ZoomView.kt
> +    private val DEFAULT_MAX_ZOOM_IN = 3.0f
с неймингом те же проблемы

2021-09-17 12:08 UTC, nqkwey commented on app/src/main/res/layout/fragment_image.xml
>              android:textColor="@color/app_title_color"
можно тут ellipsize добавить

2021-09-17 12:08 UTC, nqkwey commented on app/src/main/res/layout/fragment_image.xml
> +        <FrameLayout android:layout_width="wrap_content"
я только сейчас обратил внимание, что тут неплохая такая вложенность образовалась. Думаю, это можно исправить средствами ConstraintLayout. Но это можно оставить на потом

2021-09-21 08:23 UTC, vitalyfedorov0 requested changes
очень напутано с абстакциями в ListedFragment, но это к этому пр не относится, так что исправляй cdesc у кнопок, а с остальным потом уже будет смотреть

2021-09-21 08:23 UTC, vitalyfedorov0 commented on app/src/main/res/layout/fragment_image.xml
>              android:contentDescription="@string/view_top_bar_content_description_app_logo"
contentDescription забыл поменять; у остальных кнопок в этом хедере так же

2021-09-21 09:59 UTC, vitalyfedorov0 approved these changes

2021-09-21 10:25 UTC, merged