Feature/splash screen
Arbuss/Pine pull request #2
Opened 2021-08-27 07:55 UTC by Arbuss

Added splash screen

2021-08-27 07:57 UTC, Arbuss commented on app/src/main/java/com/rosberry/pine/ui/splash/SplashFragment.kt
> +    private fun backgroundPositioning() {
Эта функция нужна для правильного позиционирования бэкграунда. При переходе из сплеша с `windowBackground ` на фрагмент, он прыгал из-за аппаратных кнопок для навигации.

2021-08-30 12:06 UTC, nqkwey requested changes

2021-08-30 12:06 UTC, nqkwey commented on app/src/main/java/com/rosberry/pine/ui/activity/AppViewModel.kt
> +        router.navigateTo(Screens.Splash)
router.newRootScreen() иначе у тебя сплэш в бэкстеке сохраняется

2021-08-30 12:06 UTC, nqkwey commented on app/src/main/res/layout/fragment_splash.xml
> +<!--    <ImageView android:id="@+id/topLogo"-->
не надо оставлять закоменченные куски кода, всегда можно посмотреть историю изменений, если нужно вернуться к старому коду

2021-08-30 12:06 UTC, nqkwey commented on app/src/main/java/com/rosberry/pine/ui/splash/SplashViewModel.kt
> +            router.navigateTo(Screens.Main)
то же самое про router.newRootScreen()

2021-08-31 11:14 UTC, nqkwey commented on app/src/main/java/com/rosberry/pine/ui/splash/SplashFragment.kt
> +            insets
сработала все-таки штука с инсетами?

2021-08-31 11:14 UTC, nqkwey approved these changes

2021-09-01 04:27 UTC, merged