bugfix/PAA-214
Arbuss/Pine pull request #22
Opened 2021-09-28 10:09 UTC by Arbuss

2021-09-28 12:26 UTC, nqkwey requested changes

2021-09-28 12:26 UTC, nqkwey commented on app/src/main/java/com/rosberry/pine/ui/base/ListedFragment.kt
> +                            viewModel.nothingFoundHappened = true
а почему это не делать внутри viewModel?

2021-09-28 12:26 UTC, nqkwey commented on app/src/main/java/com/rosberry/pine/ui/base/ListedFragment.kt
> +                        if (viewModel.imageListIsEmpty()) {
я тут не совсем понимаю: тут imageListIsEmpty может быть не эквивалентен it.isEmpty?
кстати, мы еще обычно не используем it в проектах, а предпочитаем именовать этот параметр

2021-09-28 12:27 UTC, Arbuss commented on app/src/main/java/com/rosberry/pine/ui/base/ListedFragment.kt
> +                            viewModel.nothingFoundHappened = true
я внутри вью модели не знаю тип исключения, просто пробрасываю в фрагмент

2021-09-28 12:28 UTC, Arbuss commented on app/src/main/java/com/rosberry/pine/ui/base/ListedFragment.kt
> +                        if (viewModel.imageListIsEmpty()) {
Я это переписал в PAA-122, теперь код такой 
```
viewModel.images.collect {
    imageAdapter.setItems(it)
}
```

2021-09-29 03:46 UTC, nqkwey commented on app/src/main/java/com/rosberry/pine/ui/base/ListedFragment.kt
> +                            viewModel.nothingFoundHappened = true
как же ты не знаешь тип исключения внутри вью модели, если ты его пробрасываешь во фрагмент через вью модель? не вижу смысла в этой конструкции во фрагменте, если все это можно решить через вью модель и прокидывать эту ошибку во фрагмент только при соблюдении всех условий
```kotlin 
viewModel.nothingFoundHappened = true
if (viewModel.imageListIsEmpty()) {}
```

2021-09-29 08:19 UTC, nqkwey approved these changes

2021-09-29 08:40 UTC, merged