Feature/feed
Arbuss/Pine pull request #3
Opened 2021-08-31 10:03 UTC by Arbuss

2021-09-01 04:54 UTC, nqkwey requested changes

2021-09-01 04:54 UTC, nqkwey commented on app/src/main/java/com/rosberry/pine/data/datasource/remote/usplash/UnsplashApi.kt
> +    @Headers("Authorization: Client-ID ${BuildConfig.API_KEY}")
это можно вынести в interceptor для okhttpliclient, который потом передается в retrofit, чтобы не писать для каждого запроса

2021-09-01 04:54 UTC, nqkwey commented on app/src/main/java/com/rosberry/pine/data/repository/ImageRepository.kt
> +    suspend fun getPage(page: Int, pageLength: Int): Resource<List<Image>> = suspendCoroutine { continuation ->
тут можно в UnsplashApi сделать метод getPage тоже suspend и таким образом получится всю эту тему с continuation.resume() опустить

2021-09-01 04:54 UTC, nqkwey commented on app/src/main/java/com/rosberry/pine/di/NetworkingModule.kt
> +    @Singleton
переименовал бы UnsplashApi в PhotosApi

2021-09-01 04:54 UTC, nqkwey commented on app/src/main/java/com/rosberry/pine/data/repository/ImageRepository.kt
> +    suspend fun getPage(page: Int, pageLength: Int): Resource<List<Image>> = suspendCoroutine { continuation ->
все-таки преобразование данных в Resource<List<T>> я бы сделал в интеракторе

2021-09-01 04:54 UTC, nqkwey commented on app/src/main/java/com/rosberry/pine/ui/base/BaseAdapter.kt
> +    fun addItems(newItems: List<T>) {
почему не используешь DiffUtil для добавления элементов в список?

2021-09-01 04:54 UTC, nqkwey commented on app/src/main/java/com/rosberry/pine/ui/feed/FeedViewModel.kt
> +                    val imageWidth = screenWidth
здесь у тебя imageWidth = screenWidth, но на следующей строке ты отнимаешь imageWidth от screenWidth

2021-09-01 04:54 UTC, nqkwey commented on app/src/main/res/layout/fragment_feed.xml
> +        android:layout_width="match_parent"
внутри ConstraintLayout мы не используем match_parent, высоту и ширину можно указать в 0dp, раз ты установил констрейнты

2021-09-01 04:54 UTC, nqkwey commented on app/src/main/res/layout/fragment_main.xml
> +        android:layout_width="match_parent"
то же самое замечание про match_parent

2021-09-01 04:54 UTC, nqkwey commented on app/src/main/res/layout/fragment_main.xml
> +        android:layout_width="match_parent"
то же самое замечание про match_parent

2021-09-01 04:54 UTC, nqkwey commented on app/src/main/res/layout/item_feed.xml
> +    <ImageView android:id="@+id/image"
то же самое замечание про match_parent

2021-09-01 04:54 UTC, nqkwey commented on app/src/main/res/layout/item_feed.xml
> +        android:layout_width="match_parent"
то же самое замечание про match_parent

2021-09-01 04:54 UTC, nqkwey commented on app/src/main/res/layout/view_top_bar.xml
> +    <ImageButton android:id="@+id/app_logo"
contentDescription мы стараемся указывать для каждой ImageView/ImageButton

2021-09-01 04:54 UTC, nqkwey commented on app/src/main/res/layout/view_top_bar.xml
> +        android:layout_marginStart="16dp"
по дизайну между кнопками 24dp

2021-09-01 04:54 UTC, nqkwey commented on app/src/main/java/com/rosberry/pine/ui/main/MainFragment.kt
> +            tab.text = requireContext().resources.getStringArray(R.array.main_fragment_view_pager_tabs)
нужен ли здесь requireContext()? Можно же доступ к ресурсам получить просто через resources

2021-09-01 04:54 UTC, nqkwey commented on app/src/main/res/values/themes.xml
>          <item name="colorPrimary">@color/purple_500</item>
эти цвета тоже надо привести в соответствие с дизайном

2021-09-01 04:54 UTC, nqkwey commented on app/src/main/res/values/themes.xml
> +        <item name="android:letterSpacing">0.19</item>
поправить letterSpacing здесь

2021-09-01 04:54 UTC, nqkwey commented on app/src/main/res/values/colors.xml
> +    <color name="background_color">@color/white</color>
бэкграунд в приложении не белый, а #ededed. Мы в зеплине берем всю информацию об используемых цветах/стилях через styleguide и потом их используем в приложении
<img width="774" alt="Screenshot 2021-09-01 at 10 39 44" src="https://user-images.githubusercontent.com/3686936/131612918-edd3895c-3948-45b4-9078-fce054e1c6ca.png">

2021-09-01 04:54 UTC, nqkwey commented on app/src/main/res/values/colors.xml
> +    <color name="background_color">@color/white</color>
там же можно их представление в xml взять

2021-09-01 04:54 UTC, nqkwey commented on app/src/main/java/com/rosberry/pine/ui/activity/AppActivity.kt
> +        viewModel.openFirstScreen()
давай переименуем в showSplash()

2021-09-01 04:54 UTC, nqkwey commented on app/src/main/java/com/rosberry/pine/ui/base/BaseFragment.kt
> +        binding = null
обнулять байндинг надо в onDestroyView

2021-09-01 04:54 UTC, nqkwey commented on app/src/main/java/com/rosberry/pine/ui/feed/FeedFragment.kt
> +        binding?.feedList?.adapter = FeedAdapter()
думаю, тебе потом придется вынести FeedAdapter() в отдельное поле, чтобы постоянно не использовать эту конструкцию: (binding?.feedList?.adapter as? FeedAdapter)?

2021-09-01 04:54 UTC, nqkwey commented on app/src/main/java/com/rosberry/pine/ui/feed/FeedFragment.kt
> +    private fun getScreenWidth(): Int {
если будешь это переиспользовать, то лучше как extension вынести

2021-09-01 04:54 UTC, nqkwey commented on app/src/main/java/com/rosberry/pine/ui/feed/FeedViewModel.kt
> +                _newPage.value = Resource.Success(newPhotos.item.map { image: Image ->
отдельно вынести преобразование размера картинки

2021-09-01 06:53 UTC, Arbuss commented on app/src/main/java/com/rosberry/pine/data/repository/ImageRepository.kt
> +    suspend fun getPage(page: Int, pageLength: Int): Resource<List<Image>> = suspendCoroutine { continuation ->
Если преобразовывать все это в интеракторе, то как тогда обрабатывать ошибки с сервера? Выбрасывать исключения?

2021-09-01 06:55 UTC, Arbuss commented on app/src/main/java/com/rosberry/pine/ui/base/BaseAdapter.kt
> +    fun addItems(newItems: List<T>) {
Он тут не нужен, проблема дублей будет решаться на уровне вьюмодели, а обновление элементов не планируется, только добавление

2021-09-01 07:37 UTC, Arbuss commented on app/src/main/java/com/rosberry/pine/ui/feed/FeedViewModel.kt
> +                _newPage.value = Resource.Success(newPhotos.item.map { image: Image ->
Я могу это сделать в рамках веток пагинация? Я там этот кусок сильно поменял, не хочется возиться с конфликтами

2021-09-01 08:46 UTC, Arbuss commented on app/src/main/res/values/themes.xml
>          <item name="colorPrimary">@color/purple_500</item>
Не понимаю что туда ставить. Если с  `colorPrimary` все понятно, то `colorPrimaryVariant`, `colorSecondary`, `colorSecondaryVariant` откуда брать?

2021-09-01 11:09 UTC, nqkwey commented on app/src/main/java/com/rosberry/pine/ui/feed/FeedViewModel.kt
> +                _newPage.value = Resource.Success(newPhotos.item.map { image: Image ->
да

2021-09-01 11:17 UTC, nqkwey commented on app/src/main/java/com/rosberry/pine/ui/base/BaseAdapter.kt
> +    fun addItems(newItems: List<T>) {
Ты же в будущем будешь обновлять состояние кнопки favorite, в этот момент и пригодится diffutil. А у тебя не было проблем при пагинации и notifyItemRangeInserted?

2021-09-01 11:21 UTC, nqkwey commented on app/src/main/java/com/rosberry/pine/data/repository/ImageRepository.kt
> +    suspend fun getPage(page: Int, pageLength: Int): Resource<List<Image>> = suspendCoroutine { continuation ->
Конкретно в этом случае лучше преобразовывать исключения в определенный тип (серверная ошибка/нет соединения) и передавать это во вьюмодель

2021-09-01 11:24 UTC, Arbuss commented on app/src/main/java/com/rosberry/pine/ui/base/BaseAdapter.kt
> +    fun addItems(newItems: List<T>) {
Да, действительно, не подумал об этом. Проблема была при добавлении падало, помогло вот это `itemAnimator = null`

2021-09-01 11:26 UTC, nqkwey commented on app/src/main/res/values/themes.xml
>          <item name="colorPrimary">@color/purple_500</item>
эти моменты надо уточнять с дизайнером, в нашем случае colorPrimary/colorSecondary - это main1/main2 в зависимости от темы приложения, colorPrimaryVariant - пусть будет main1_60, colorSecondaryVariant - main2_60

2021-09-01 12:03 UTC, nqkwey commented on app/src/main/java/com/rosberry/pine/di/NetworkingModule.kt
> +            chain.run {
обычно мы выносим все интерсепторы в отдельные классы

2021-09-01 12:03 UTC, nqkwey commented on app/src/main/res/values-night/themes.xml
> +    <style name="Theme.Pine" parent="Theme.MaterialComponents.DayNight.NoActionBar">
тут надо исправить согласно последним комментариям

2021-09-01 12:03 UTC, nqkwey commented on app/src/main/java/com/rosberry/pine/data/repository/ImageRepository.kt
> +    suspend fun getPage(page: Int, pageLength: Int): Resource<List<Image>> {
я тут имел в виду, чтобы преобразование в ресурс происходило в интеракторе, репозиторий возвращал бы просто List<Image>

2021-09-02 11:23 UTC, nqkwey approved these changes

2021-09-02 11:23 UTC, nqkwey commented on app/src/main/res/layout/view_top_bar.xml
>          android:layout_width="0dp"
тут бы я добавил includeFontPadding="false"

2021-09-03 04:55 UTC, merged